name: CI
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo fmt --all -- --check
  deploy:
    runs-on: ubuntu-latest
    needs: check
    environment: deployment
    if: github.ref_name == 'main'
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: the7winds/dilbert-bot:latest