name: Deploy
on: [push]
#  push:
#    branches:
#      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: the7winds/dilbert-bot:latest
